### ISSUE TITLE
check :todo for updates

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#111]
# Description/Steps to reproduce

**will be a lot of paperwork. Will give you time to look at files, read some comments and give some insights how code can be improved**

When you'll be more than familiar with project structure I think you'll be able to find by yourself what can be improved. 
I've put a lot of marks in files. sometimes I understand that it can be done with the better way, but I was lazy and don't want to spend a lot of time. 

So, how you can find my **todo** marks. This also show you how often I add comments, and hope this will teach you to leave comments in your code too :)

- [ ] Ctrl+F ":todo" on top folder
- [ ] prepare list with updates with links to code, like: https://github.com/atherdon/groceristar/blob/master/server/like-middleware-helper.js#L17
- [ ] 
- [ ] Sort by priority and understanding. Each update must have at least separated commit, but pull-request will be better.
- [ ] In comments we'll discuss which :todo `s is not clear

# Expected result

# Additional information
