### ISSUE TITLE
Easy and small tasks (Release 1.3 and more)

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#215]
# Description/Steps to reproduce

### Release 1.3.1 (it's like a clean up of clean up)

- [ ] #291 First steps. Very easy task list for juniors

- [ ] It's simple: enable features that were hidden and try to add all features, listed on the homepage

- [ ] If intern has skills in front-end we can make this site mobile-ready and work fast by making builds for static files.

- [ ] Also, we can update some folder structure. Sometimes it's really confusing.

- [ ] Update readme, so any can follow steps from scratch and run this project.
- [ ] Enable middleware in a right way

### Release 1.3.2

- [ ] #293 Complete second step lists, created for junior interns

### Release 1.3.3 

- [ ] enable favs & purchased, create an empty list, 
- [ ] add to an empty list departments
- [ ]  move between departments
- [ ]  Run tests script
- [ ] Hide or delete unnecessary Departments

### Easy (clean up №1 of all issue mess)

- [ ] #13 View information outside the profile

- [ ] #86 Allow users to create a departments First part is not complex. Can be high-priority
- [ ] #167 Setup gitignore settings
- [x] #121 + Convert landing template into landosik template
- [ ] #196 Clean up folder structures
- [ ] #168 get rid of route that i use for testing only purposes
- [ ] #143 Form with this action wouldn't work right now. discussion
- [ ] #133 **Create profile, settings page**
- [ ] #78 **Logged in user can open login page**. Make a redirect
- [ ] #95 **Fix method Grocery.createnew** (grocery list i assume???)

- [ ] #91 **Review and update Favourite url slug**
- [ ] #99 I comment(hide part of code, because it working bad). Maybe we'll solve that by going from pug to react
- [ ] #186 When you try to open page when you **don't logged in you get an error**, because you don't pass stuff like userId, etc
- [ ] #179 **Create dropdown list with items** - links to your created previously groceries

### Later

- [ ] #93 **Add to Grocery list from favourite list** .is for late stages
- [ ] #137 **Move ingredients between departments.** complex while we don't have a clear plan how to do it
- [ ] #102 **Move created ingredient from one departemnt into another.** is this a duplicate?
- [ ] #194 **Duplicated controller methods for different user states.**
- [ ] #182 **we always get a ultimate grocery id and add it into links. we can update it**
- [ ] #192 **We need to find another way, how to pass variables into jquery app.js file.**
- [ ] #155 **Update items order after click on link - clear purchased**
- [ ] #51 **Relations at user models.** or we can skip it
- [ ] #244 **Data Migration**.  not easy, but funny thing. also will hard teach how to operate with data in objects. can be split to a few tasks and moved to easy
- [ ] #15 **Grocery try to combine same ingredients** We need to discuss this feature, it can affect a lot of small functionality. It'll be a job to create a plan with suggestions and step-by-step task list. if it'll require my help - buzz me. Late stages only. After Release 1.3
