### ISSUE TITLE
todo upd

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#246]
# Description/Steps to reproduce

- [x] footertemplate: filter must have event bind with some sort of ajax js redirect.

i'll need to retest all css nice look-and-feel thngs

- [x] like hover show delete icon
- [x] double click hide x icon and hide label with title, then it's enable input with value from label
- [ ] think if we can add sortable stuff.... #135 

i need to test all features, that we have before

- [x] rename custom
- [x] rename ultimate
- [x] purchase
- [x] un-toggle
- [x] toggle-all
- [x] destroy / destroy all
- [x] IS ULTIMATE

# Expected result

# Additional information
