### ISSUE TITLE
First steps. Task list for Release 1.3 intern ready

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#291]
# Description/Steps to reproduce

- [ ] update merge/import scripts. You quite a familiar with work of this files, so it's easy to with my explanation. just need to add code and test. #253

- [ ] #208 this issue must be updated. because I created a new way for displaying select. Please start to digg it by self and start some discussion with me at comments of that task. 
_Right now on master we have 2-3 selects. so before start - we need to discuss plan on this task._

- [ ] #251 Try to reproduce this issue by self. It has an easy part, but you need to find it first.

- [x] #290 is a duplicate, but with better explanation

- [ ] #225 this is a funny task because you'll try to broke and then to fix my buggy code. 

small tasks, related to touching some files. all these tasks related to adding some predefined piece of code and test, if this code has appeared at HTML pages(reviewing source code in the browser)

- [ ] #221 robots help us

- [ ] #98 sumo me install

- [ ] #222 drift install

# Expected result

# Additional information

**Comment by yxie66** [comment]
Thank you very much for this instruction!

**Comment by atherdon** [comment]
Hope I generate a lot of emails on your inbox. but a lot of things will be easier from now

**Comment by yxie66** [comment]
Yes, absolutely it will! By the way, I think I have merged the master and develop branches before, do you expect me to complete it on the 1.1 version? If so, I could replace my repo with the 1.1 version. What's more, do you expect these tasks completed on my repo or yours, or both? Sorry for asking these questions.

**Comment by atherdon** [comment]
this is awesome that you're asking questions. because it's saves time.
I like questions 😉 because if you're not asking questions - it's a big
probability that you're stuck at something.
will answer at merge task

**Comment by yxie66** [comment]
update: 1.1 version on my own remote branch already.
next: import db logic to readme
