### ISSUE TITLE
Second steps 

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#293]
# Description/Steps to reproduce
This task will relate more coding

- [ ]  #176 Constantine find few bugs that must be addressed

- [ ] #201 move routes that i forget to move to grocery controllers + #202 Similar but move from routes to departments controllers

- [ ] #164 finish this router get hidden by groceryId

- [ ] #159 link not working, it's not important because not used. we need to decide what we'll do with it

- [ ] #228 jquery duplicate. Migrate old version to a new one, test it carefully

# Expected result

# Additional information
