### ISSUE TITLE
Homework task list

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#317]
# Description/Steps to reproduce

- [ ] #43 The easiest way is to buzz me. some part of the information stored at recipe-api project. some part of work is related to #278, all data can be viewed at localhost/explorer

- [ ] #114 Before the start, I require a simple discussion at comments for a better plan

- [ ] #111 Important for your future work

- [x] #195 it's homework too. Not very useful for this project stage, but will give a lot of information later, will help builds, will help to create a better continuous integration. it's like a going to a mid-school of development

**Comment by atherdon** [comment]
#316
